// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAhwBrsfgkjKfGi6_gQ9h6oI-mO7EdoIo',
    appId: '1:510752503145:web:7b712c7896556baab1f9f8',
    messagingSenderId: '510752503145',
    projectId: 'uas-mobprog-f4393',
    authDomain: 'uas-mobprog-f4393.firebaseapp.com',
    storageBucket: 'uas-mobprog-f4393.firebasestorage.app',
    measurementId: 'G-5G2DQW8THG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG7CDCxNJuEsgw0cZX_skPSGA1MXWonys',
    appId: '1:510752503145:android:acc6a8fcbd4475ffb1f9f8',
    messagingSenderId: '510752503145',
    projectId: 'uas-mobprog-f4393',
    storageBucket: 'uas-mobprog-f4393.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4wSPZVjUpaTaLx-WW8cG8RgnxXVTeCD0',
    appId: '1:510752503145:ios:85f1fd1863f8e66cb1f9f8',
    messagingSenderId: '510752503145',
    projectId: 'uas-mobprog-f4393',
    storageBucket: 'uas-mobprog-f4393.firebasestorage.app',
    iosBundleId: 'com.example.uasMobprog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4wSPZVjUpaTaLx-WW8cG8RgnxXVTeCD0',
    appId: '1:510752503145:ios:85f1fd1863f8e66cb1f9f8',
    messagingSenderId: '510752503145',
    projectId: 'uas-mobprog-f4393',
    storageBucket: 'uas-mobprog-f4393.firebasestorage.app',
    iosBundleId: 'com.example.uasMobprog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAhwBrsfgkjKfGi6_gQ9h6oI-mO7EdoIo',
    appId: '1:510752503145:web:2218606cf3454516b1f9f8',
    messagingSenderId: '510752503145',
    projectId: 'uas-mobprog-f4393',
    authDomain: 'uas-mobprog-f4393.firebaseapp.com',
    storageBucket: 'uas-mobprog-f4393.firebasestorage.app',
    measurementId: 'G-Q4H1WPZPYN',
  );
}
